// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp;
// using Microsoft.CodeAnalysis.CSharp.Syntax;
// using Microsoft.CodeAnalysis.Diagnostics;
// using SourceGenUtils;
//
// namespace MultiplayerModel.Generators.Controller.Diagnostics;
//
// public static class UseControllerMethodDiagnostic
// {
//     public const string DiagnosticId = "UseControllerMethod";
//     private const string Title = "Use the auto-generated controller method";
//
//     private const string MessageFormat =
//         "This method has an auto-generated wrapper method that synchronises its call between multiple clients and should be used in order to ensure consistency";
//
//     private const string Category = "Usage";
//
//     public static readonly DiagnosticDescriptor Diagnostic = new
//     (
//         DiagnosticId,
//         Title,
//         MessageFormat,
//         Category,
//         DiagnosticSeverity.Warning,
//         isEnabledByDefault: true,
//         description: null
//     );
//     
//     public static void RegisterForAnalysis(AnalysisContext context)
//     {
//         context.RegisterSyntaxNodeAction(Analyze, SyntaxKind.InvocationExpression);
//     }
//     
//     public static void Analyze(SyntaxNodeAnalysisContext context)
//     {
//         if (context.IsGeneratedCode)
//             return; // TODO: Just skip code generated by the specific generator, not all of them
//
//         var invocation = (InvocationExpressionSyntax)context.Node;
//
//         var methodSymbol = context
//             .SemanticModel
//             .GetSymbolInfo(invocation, context.CancellationToken)
//             .Symbol as IMethodSymbol;
//
//         if (methodSymbol!.HasAttribute<MessageHandlerAttribute>())
//         {
//             context.ReportDiagnostic
//             (
//                 Microsoft.CodeAnalysis.Diagnostic.Create
//                 (
//                     Diagnostic,
//                     invocation.GetLocation()
//                 )
//             );
//         }
//     }
// }